### ISSUE TITLE
Aliases/implications with errors

### ISSUE THREAD

**Issue by ToksT** [r888888888/danbooru#2468]
http://danbooru.donmai.us/tag_aliases
http://danbooru.donmai.us/tag_implications

There are a lot of aliases and implications with errors. They all seem to be from within the last month.

The errors:
`error: undefined method 'is_moderator?' for nil:NilClass`
`error: undefined method '>=' for nil:NilClass`

**Comment by r888888888** [comment]
This is being fixed now.

**Comment by ToksT** [comment]
The bug still exists for implications, it was only fixed for aliases: http://danbooru.donmai.us/tag_implications
