### ISSUE TITLE
Wiki Pages Being Updated Erroneously on Artist Edits

### ISSUE THREAD

**Issue by BrokenEagle** [r888888888/danbooru#2974]
I noticed recently that when updating an artist with a wiki page, it always sets the "updated_at" and "updater_id" fields even when nothing is behing updated.  Additionally, no new wiki versions are created.

Example:

http://danbooru.donmai.us/wiki_pages/33022.json
http://danbooru.donmai.us/wiki_page_versions?search%5Bwiki_page_id%5D=33022

It has me listed as the most recent updater, yet you can see from the history that a new version was not created.

**Comment by evazion** [comment]
The cause looks to be this:

* the artist model declares `accepts_nested_attributes_for :wiki_page`.
* using nested attributes enables autosave for that association ([1]).
* autosave causes the wiki page to be saved whenever the artist is saved ([2]).
* the wiki page model has an `initialize_updater` callback that sets the updater on each save, whether or not the wiki was actually updated.
* changing the updater also bumps the timestamp.

So it's not just artist wikis, saving any wiki page without changing it bumps `updated_at` and `updater_id`.

I think the `updater_id` field could just be dropped. It should always be the same thing as the updater of the last wiki page version.

[1]: http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html
[2]: http://api.rubyonrails.org/classes/ActiveRecord/AutosaveAssociation.html

**Comment by evazion** [comment]
It looks like there are ~11,000 wiki pages whose `creator_id` doesn't match the first version, and ~1100 whose `updater_id` doesn't match the last version.

```sql
-- wiki pages whose creator doesn't match that of the first version (~11,000 rows).
SELECT COUNT(*) 
FROM wiki_pages wp 
JOIN wiki_page_versions wpv 
  ON wp.id = wpv.wiki_page_id 
WHERE
   wpv.id IN (SELECT MIN(id) FROM wiki_page_versions GROUP BY wiki_page_id)
   AND wp.creator_id != wpv.updater_id;

-- wiki pages whose updater doesn't match that of the last version (~1100 rows).
SELECT COUNT(*) 
FROM wiki_pages wp 
JOIN wiki_page_versions wpv 
  ON wp.id = wpv.wiki_page_id 
WHERE
   wpv.id IN (SELECT MAX(id) FROM wiki_page_versions GROUP BY wiki_page_id)
   AND wp.updater_id != wpv.updater_id;

**Comment by evazion** [comment]
I experimented with dropping the `updater_id` and `creator_id` columns. It's doable by adding some associations on the wiki page model:

```ruby
# alternative option
# has_one :initial_version, -> { where(id: select("DISTINCT ON (wiki_page_id) id").order(:wiki_page_id, id: :asc)) }, :class_name => "WikiPageVersion"
# has_one :current_version, -> { where(id: select("DISTINCT ON (wiki_page_id) id").order(:wiki_page_id, id: :desc)) }, :class_name => "WikiPageVersion"

has_one :initial_version, lambda { where(id: select("min(id)").group(:wiki_page_id)) }, :class_name => "WikiPageVersion"
has_one :current_version, lambda { where(id: select("max(id)").group(:wiki_page_id)) }, :class_name => "WikiPageVersion"
has_one :updater, :through => :initial_version
has_one :creator, :through => :initial_version, :source => :updater
```

Normalizing the table like this avoids consistency problems with the `creator_id` and  `updater_id`. The resulting queries *are* slower though, about ~350ms on my machine. Not horrendously slow, but enough to be noticeable. So I'll that idea aside.

**Comment by r888888888** [comment]
Fixed in 68f057e7ba0fae090c14afe8169808cf4f34803e

**Comment by evazion** [comment]
Just noticed this is a dupe of #1021.

> Fixed in 68f057e

That fixes it for artist entries, but it can still happen if you go to `/wiki_pages` and save a wiki page without making any changes.

**Comment by BrokenEagle** [comment]
The above commit doesn't seem to be working in preventing erroneous updates to the corresponding artist wiki entries.

Recent example:

[Artist (JSON)](http://danbooru.donmai.us/artists/71285.json)
[Wiki page (JSON)](http://danbooru.donmai.us/wiki_pages/51459.json)
[Wiki page versions](http://danbooru.donmai.us/wiki_page_versions?search%5Bwiki_page_id%5D=51459)

For the above example, I only edited the URLs and not the Body for that artist, and after saving, it updated the wiki page even though a new version was not created.

Contrast that with an artist entry (with a wiki) updated from the API.

[Artist (JSON)](http://danbooru.donmai.us/artists/38609.json)
[Wiki page (JSON)](http://danbooru.donmai.us/wiki_pages/31529.json)
[Wiki page versions](http://danbooru.donmai.us/wiki_page_versions?search%5Bwiki_page_id%5D=31529)

For the above example, only the artist entry was updated. Could the input page be part of the problem as well...?

**Comment by BrokenEagle** [comment]
It seems that edits through the API are now causing updates to the wikis as well, but a new wiki version is still not being created.

For the following, the update request (`PUT`) was sent with only the `artist[url_string]` set.

Artist version: http://danbooru.donmai.us/artist_versions?search%5Bartist_id%5D=140023&page=b416961&limit=1
Wiki data (JSON): http://danbooru.donmai.us/wiki_pages/79618.json
Wiki versions: http://danbooru.donmai.us/wiki_page_versions?search%5Bwiki_page_id%5D=79618
