### ISSUE TITLE
Routing Error when uploading images

### ISSUE THREAD

**Issue by chibiisyourworstnightmare** [r888888888/danbooru#3749]
Deployed using cap just fine but on production uploading an image yields this. 
[ https://i.imgur.com/R5T6D6J.png](url)
Trying to go through with the upload anyways returns a page that says:
`ActiveRecord::RecordInvalid exception raised Validation failed:` 
`Md5 confirmation doesn't match Md5`
`app/logical/upload_service.rb:500:in start!`
`app/controllers/uploads_controller.rb:54:in create`

Running under `bundle exec rails server` returns a much more descriptive error.

``Routing Error No route matches [POST] "/uploads/preprocess" Rails.root: /var/www/danbooru2/releases/20180617194752 Framework Trace actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call' actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call' railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app' railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call' activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged' activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged' activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged' railties (5.2.0) lib/rails/rack/logger.rb:26:in `call' sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call' actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call' actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call' rack (2.0.5) lib/rack/method_override.rb:22:in `call' rack (2.0.5) lib/rack/runtime.rb:22:in `call' activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call' actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call' actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call' rack (2.0.5) lib/rack/sendfile.rb:111:in `call' railties (5.2.0) lib/rails/engine.rb:524:in `call' rack (2.0.5) lib/rack/handler/webrick.rb:86:in `service' /home/danbooru/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service' /home/danbooru/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run' /home/danbooru/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread' Full Trace actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call' actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call' railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app' railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call' activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged' activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged' activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged' railties (5.2.0) lib/rails/rack/logger.rb:26:in `call' sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call' actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call' actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call' rack (2.0.5) lib/rack/method_override.rb:22:in `call' rack (2.0.5) lib/rack/runtime.rb:22:in `call' activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call' actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call' actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call' rack (2.0.5) lib/rack/sendfile.rb:111:in `call' railties (5.2.0) lib/rails/engine.rb:524:in `call' rack (2.0.5) lib/rack/handler/webrick.rb:86:in `service' /home/danbooru/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service' /home/danbooru/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run' /home/danbooru/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread' ``

I ran an interactive rails console and `Post.count` is returning 0.  I am posting using an admin account and it does show up when running `User.find(1)`

Unicorn logs are reporting a 404 as seen here `[17/Jun/2018:15:10:09 -0500] "POST /404 HTTP/1.0" 404 34 0.0919`

I've tinkered with the routing.rb, production.rb files as well as the model file for uploads, and the two files brought up in the error above but my understanding of ruby is tenuous at best.  Any help would be much appreciated.

**Comment by r888888888** [comment]
I assume you're not uploading directly from imgur.

Are you using the drag and drop or are you browsing to the file?

**Comment by r888888888** [comment]
This should be fixed in cc24b0a54f6a6d0c0edf8ead8a191f758b5e0795

**Comment by chibiisyourworstnightmare** [comment]
I am using drag and drop, sorry for the confusion, wasn't sure what the meta was for uploading images to the issues page.

The error persists in the same form.  Here is some more output from the rails server.

``::1 - - [18/Jun/2018:18:54:04 CDT] "GET /related_tag.json?query=&category= HTTP/1.1" 304 0
http://localhost:3000/uploads/new -> /related_tag.json?query=&category=
[PID:584] Started POST "/uploads/preprocess" for ::1 at 2018-06-18 18:54:06 -0500
[PID:584]   
[PID:584] ActionController::RoutingError (No route matches [POST] "/uploads/preprocess"):
[PID:584]   
[PID:584] actionpack (5.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
[PID:584] actionpack (5.2.0) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
[PID:584] railties (5.2.0) lib/rails/rack/logger.rb:38:in `call_app'
[PID:584] railties (5.2.0) lib/rails/rack/logger.rb:26:in `block in call'
[PID:584] activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `block in tagged'
[PID:584] activesupport (5.2.0) lib/active_support/tagged_logging.rb:28:in `tagged'
[PID:584] activesupport (5.2.0) lib/active_support/tagged_logging.rb:71:in `tagged'
[PID:584] railties (5.2.0) lib/rails/rack/logger.rb:26:in `call'
[PID:584] sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
[PID:584] actionpack (5.2.0) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
[PID:584] actionpack (5.2.0) lib/action_dispatch/middleware/request_id.rb:27:in `call'
[PID:584] rack (2.0.5) lib/rack/method_override.rb:22:in `call'
[PID:584] rack (2.0.5) lib/rack/runtime.rb:22:in `call'
[PID:584] activesupport (5.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[PID:584] actionpack (5.2.0) lib/action_dispatch/middleware/executor.rb:14:in `call'
[PID:584] actionpack (5.2.0) lib/action_dispatch/middleware/static.rb:127:in `call'
[PID:584] rack (2.0.5) lib/rack/sendfile.rb:111:in `call'
[PID:584] railties (5.2.0) lib/rails/engine.rb:524:in `call'
[PID:584] rack (2.0.5) lib/rack/handler/webrick.rb:86:in `service'
[PID:584] /home/danbooru/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:140:in `service'
[PID:584] /home/danbooru/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/httpserver.rb:96:in `run'
[PID:584] /home/danbooru/.rbenv/versions/2.5.1/lib/ruby/2.5.0/webrick/server.rb:307:in `block in start_thread'
::1 - - [18/Jun/2018:18:54:06 CDT] "POST /uploads/preprocess HTTP/1.1" 404 3304
http://localhost:3000/uploads/new -> /uploads/preprocess``

**Comment by r888888888** [comment]
I would make sure you have the latest code and also check for any Javascript errors in your console.

**Comment by chibiisyourworstnightmare** [comment]
Javascript console reports a 500 internal server error.  Looking through /var/www/danbooru2/current/ manually confirms that the code is up to date.

**Comment by r888888888** [comment]
You restarted the server as well?

**Comment by chibiisyourworstnightmare** [comment]
I looked a little deeper after the issue persisted after a restart and found in developer console under the preprocess file this error:
``"PG::NotNullViolation: ERROR:  null value in column "id" violates not-null constraint↵DETAIL:  Failing row contains (null, null, null, null, q, 1, 127.0.0.1, tagme, error: ActiveRecord::NotNullViolation - PG::NotNullViolation: ER..., /var/www/danbooru2/shared/bundle/ruby/2.5.0/gems/activerecord-5...., null, null, 2018-06-19 22:43:04.221464, 2018-06-19 22:43:04.434312, server, null, 251aed5175936fe9650c7f9c8f39d8f5, png, 193222, 323, 394, null, null, null, null).↵: UPDATE "uploads" SET "id" = $1, "status" = $2, "backtrace" = $3, "updated_at" = $4, "md5" = $5, "file_ext" = $6, "file_size" = $7, "image_width" = $8, "image_height" = $9 WHERE "uploads"."id" = $10"``

**Comment by chibiisyourworstnightmare** [comment]
Interestingly enough the `last_value` in the `public.uploads_id_seq` regclass is incriminating with every post and I can see all the uploads as reprocessing.  Still gives the `Md5 confirmation doesn't match Md5` error when submitting.  However, the routing error has gone away.

**Comment by r888888888** [comment]
That looks to me like you haven't updated the code to the latest. Or maybe the server hasn't been restarted to load the new code.

You could try deleting all the uploads in the database.

**Comment by chibiisyourworstnightmare** [comment]
Yup, redeployed and that fixed everything.  Thanks for your time and help!
