### ISSUE TITLE
Duplicate errors since updating

### ISSUE THREAD

**Issue by Iratu** [r888888888/danbooru#3772]
Heya, Since updating to the latests commit (today) I've been having the following issue: 
```

ActiveRecord::RecordInvalid exception raised

    Validation failed: Md5 confirmation doesn't match Md5
    app/logical/upload_service.rb:529:in `start!'
    app/controllers/uploads_controller.rb:54:in `create'

```

I've tried disabling the `validate_md5_uniqueness(record)` but it still gives that error when trying to upload.

It gives the error on any file I try to upload.

**Comment by r888888888** [comment]
What file/URL triggers this?

Also, I've been getting a lot of random error emails that are probably from other instances of Danbooru. This is fixed in master already but you should update any reference to webmaster@danbooru.donmai.us and r888888888@gmail.com in your codebase to point to an address you control to help you debug these issues.

**Comment by r888888888** [comment]
I believe most of the outstanding issues with failing uploads are resolved now. Let me know if you update and still see issues.

**Comment by Iratu** [comment]
I've updated and I'm still having the issue mentioned in the OP, does it do any kind of MD5 check with iqdbs?

**Comment by r888888888** [comment]
No, IQDBS shouldn't have a factor.

How are you uploading the post?

**Comment by Iratu** [comment]
I've made a small video on how I'm uploading it, Note: logo is NSFW
[2018-07-13 21-06-51.zip](https://github.com/r888888888/danbooru/files/2193891/2018-07-13.21-06-51.zip)
