### ISSUE TITLE
Recommended page is broken

### ISSUE THREAD

**Issue by nonamethanks** [r888888888/danbooru#3876]
Also reported in the forum and verified by me. Accessing the [recommended page](https://danbooru.donmai.us/recommended_posts?context=user) from the topbar link returns
```ruby
JSON::ParserError exception raised
765: unexpected token at '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"> <title>500 Internal Server Error</title> <h1>Internal Server Error</h1> <p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p> '
app/models/recommender_service.rb:31:in `block in recommend_for_user'
app/logical/cache.rb:18:in `get'
app/models/recommender_service.rb:21:in `recommend_for_user'
app/models/recommender_service.rb:56:in `recommend'
app/controllers/recommended_posts_controller.rb:20:in `load_posts'
app/controllers/recommended_posts_controller.rb:6:in `show'
```

And visiting it [directly](https://danbooru.donmai.us/recommended_posts) instead returns
```ruby
ActionView::Template::Error exception raised
undefined method `empty?' for nil:NilClass
app/presenters/post_set_presenters/base.rb:10:in `post_previews_html'
app/presenters/post_set_presenters/post.rb:15:in `post_previews_html'
app/views/recommended_posts/_show.html.erb:2:in `_app_views_recommended_posts__show_html_erb__1276633261318179633_69978811940440'
app/views/recommended_posts/show.html.erb:7:in `_app_views_recommended_posts_show_html_erb__536710504257313823_69978812002760'
```

**Comment by r888888888** [comment]
This should be fixed now. The direct URL is https://danbooru.donmai.us/recommended_posts?context=user

**Comment by nonamethanks** [comment]
@r888888888 is the change deployed? I still get the same error.

**Comment by r888888888** [comment]
My bad. It worked for me because my user id index was 0. I've updated the recommender service and it should be fixed for everyone now.
